"""AI engines: configuration overrides, the request trace, produced files, prompt templates
and reusable characters; ``generated_content.ai_request_id``.

Hand-written DDL (no autogenerate), like 0001-0005. app/models.py mirrors it. Additive only;
the downgrade drops only these objects (files under UPLOAD_DIR/ai stay).

- ``ai_engine_configs``: an admin's override per engine (NULL = the AI_<ENGINE>_* environment
  value). No secret column: ``credentials_ref`` names an AI_CRED_* environment variable.
- ``ai_requests``: one engine execution (status succeeded | failed | not_configured |
  rejected | pending), the minimised input and its hash, provider, model, validated output,
  validation, error code, usage, estimated cost, attempts, duration. Deleted with the child.
- ``ai_request_events``: append-only execution log (codes and numbers only; a trigger
  refuses UPDATE and DELETE except the child/request cascade).
- ``ai_assets``: produced files (image | audio | video | document) under UPLOAD_DIR/ai.
- ``ai_prompt_templates``: versioned instructions per engine, task and language.
- ``ai_characters``: reusable character specifications.

Revision ID: 0006
Revises: 0005
Create Date: 2026-10-06
"""
from alembic import op

revision = "0006"
down_revision = "0005"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("""
CREATE TABLE ai_engine_configs (
  engine text PRIMARY KEY CHECK (engine ~ '^[a-z_]{2,40}$'),
  enabled boolean,
  provider text CHECK (provider ~ '^[a-z0-9][a-z0-9_-]{0,39}$'),
  model text CHECK (length(model) <= 120),
  endpoint text CHECK (endpoint ~ '^https://'),
  credentials_ref text CHECK (credentials_ref ~ '^AI_CRED_[A-Z0-9_]{1,60}$'),
  timeout_seconds integer CHECK (timeout_seconds BETWEEN 5 AND 600),
  max_retries integer CHECK (max_retries BETWEEN 0 AND 5),
  max_output integer CHECK (max_output > 0),
  daily_cost_limit numeric(12,4) CHECK (daily_cost_limit >= 0),
  unit_cost numeric(14,8) CHECK (unit_cost >= 0),
  safety_level text CHECK (safety_level IN ('strict','standard')),
  fallback_provider text CHECK (fallback_provider ~ '^[a-z0-9][a-z0-9_-]{0,39}$'),
  fallback_model text CHECK (length(fallback_model) <= 120),
  updated_by uuid REFERENCES users(id),
  updated_at timestamptz NOT NULL DEFAULT now()
)
""")
    op.execute("""
CREATE TABLE ai_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  pipeline_id uuid,
  parent_request_id uuid REFERENCES ai_requests(id) ON DELETE SET NULL,
  engine text NOT NULL,
  task text NOT NULL,
  status text NOT NULL CHECK (status IN ('succeeded','failed','not_configured','rejected','pending')),
  provider text,
  model text,
  fallback_used boolean NOT NULL DEFAULT false,
  child_id uuid REFERENCES children(id) ON DELETE CASCADE,
  user_id uuid REFERENCES users(id),
  language text NOT NULL,
  input jsonb NOT NULL DEFAULT '{}'::jsonb,
  input_hash text NOT NULL,
  context_version text,
  template_id uuid,
  output jsonb,
  validation jsonb,
  error_code text,
  error_message text,
  retryable boolean NOT NULL DEFAULT false,
  usage jsonb NOT NULL DEFAULT '{}'::jsonb,
  cost_estimate numeric(14,6) NOT NULL DEFAULT 0,
  attempts integer NOT NULL DEFAULT 0,
  duration_ms integer,
  job_id text,
  provider_request_id text,
  created_at timestamptz NOT NULL DEFAULT now(),
  finished_at timestamptz
)
""")
    op.execute("CREATE INDEX ai_requests_engine_created_idx ON ai_requests (engine, created_at DESC)")
    op.execute("CREATE INDEX ai_requests_child_idx ON ai_requests (child_id, created_at DESC) WHERE child_id IS NOT NULL")
    op.execute("CREATE INDEX ai_requests_pipeline_idx ON ai_requests (pipeline_id) WHERE pipeline_id IS NOT NULL")
    op.execute("CREATE INDEX ai_requests_pending_idx ON ai_requests (status) WHERE status = 'pending'")
    op.execute("""
CREATE TABLE ai_request_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id uuid NOT NULL REFERENCES ai_requests(id) ON DELETE CASCADE,
  at timestamptz NOT NULL DEFAULT now(),
  kind text NOT NULL,
  detail jsonb NOT NULL DEFAULT '{}'::jsonb
)
""")
    op.execute("CREATE INDEX ai_request_events_request_idx ON ai_request_events (request_id, id)")
    # The execution log is append-only; rows go only with their request (cascade).
    op.execute("""
CREATE FUNCTION ai_request_events_append_only() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP = 'UPDATE' THEN
    RAISE EXCEPTION 'ai_request_events are append-only';
  END IF;
  IF EXISTS (SELECT 1 FROM ai_requests WHERE id = OLD.request_id) THEN
    RAISE EXCEPTION 'ai_request_events are deleted only together with their request';
  END IF;
  RETURN OLD;
END $$
""")
    op.execute("""
CREATE TRIGGER ai_request_events_append_only BEFORE UPDATE OR DELETE ON ai_request_events
FOR EACH ROW EXECUTE FUNCTION ai_request_events_append_only()
""")
    op.execute("""
CREATE TABLE ai_assets (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  request_id uuid NOT NULL REFERENCES ai_requests(id) ON DELETE CASCADE,
  child_id uuid REFERENCES children(id) ON DELETE CASCADE,
  kind text NOT NULL CHECK (kind IN ('image','audio','video','document')),
  mime text NOT NULL,
  path text NOT NULL,
  size_bytes integer NOT NULL CHECK (size_bytes >= 0),
  sha256 text NOT NULL,
  meta jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
)
""")
    op.execute("CREATE INDEX ai_assets_request_idx ON ai_assets (request_id)")
    op.execute("""
CREATE TABLE ai_prompt_templates (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  engine text NOT NULL,
  task text NOT NULL,
  language text NOT NULL,
  version integer NOT NULL CHECK (version > 0),
  body text NOT NULL CHECK (length(body) BETWEEN 1 AND 20000),
  active boolean NOT NULL DEFAULT true,
  created_by uuid REFERENCES users(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (engine, task, language, version)
)
""")
    op.execute("""
CREATE TABLE ai_characters (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  child_id uuid REFERENCES children(id) ON DELETE CASCADE,
  name_token text NOT NULL CHECK (name_token ~ '^[a-z0-9_]{1,40}$'),
  spec jsonb NOT NULL DEFAULT '{}'::jsonb,
  request_id uuid REFERENCES ai_requests(id) ON DELETE SET NULL,
  created_by uuid REFERENCES users(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
)
""")
    op.execute("ALTER TABLE generated_content ADD COLUMN ai_request_id uuid REFERENCES ai_requests(id) ON DELETE SET NULL")


def downgrade() -> None:
    op.execute("ALTER TABLE generated_content DROP COLUMN IF EXISTS ai_request_id")
    op.execute("DROP TABLE IF EXISTS ai_characters")
    op.execute("DROP TABLE IF EXISTS ai_prompt_templates")
    op.execute("DROP TABLE IF EXISTS ai_assets")
    op.execute("DROP TRIGGER IF EXISTS ai_request_events_append_only ON ai_request_events")
    op.execute("DROP TABLE IF EXISTS ai_request_events")
    op.execute("DROP FUNCTION IF EXISTS ai_request_events_append_only()")
    op.execute("DROP TABLE IF EXISTS ai_requests")
    op.execute("DROP TABLE IF EXISTS ai_engine_configs")
